apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: order-service
        image: ghcr.io/zzzang12-cns/order-service
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 9002
        env:
        - name: POLAR_CATALOG_SERVICE_URI
          value: catalog-service.default.svc.cluster.local
        - name: SPRING_CLOUD_CONFIG_URI
          value: config-service.default.svc.cluster.local
        - name: SPRING_R2DBC_URL
          value: r2dbc:postgresql://polar-postgres.default.svc.cluster.local/polardb_order
        - name: SPRING_FLYWAY_URL
          value: jdbc:postgresql://polar-postgres.default.svc.cluster.local/polardb_order